In [1]:
import torch

In [2]:
print(torch.__version__)

1.12.1


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [7]:
vector = torch.tensor([23, 34, 456])
vector

tensor([ 23,  34, 456])

In [9]:
vector.shape

torch.Size([3])

In [11]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2936, 0.8688, 0.7459, 0.2762],
        [0.8098, 0.5781, 0.8162, 0.3814],
        [0.8938, 0.2113, 0.1815, 0.7414]])

In [12]:
random_tensor.shape

torch.Size([3, 4])

In [13]:
random_tensor.ndim

2

In [14]:
tensor = torch.tensor([12, 2])
tensor

tensor([12,  2])

In [15]:
tensor + 10

tensor([22, 12])

In [16]:
torch.tensor([1, 3, 6]) * torch.tensor([22 , 1, 4])

tensor([22,  3, 24])

In [17]:
tensor_1 = torch.arange(1., 10.)
tensor_1

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
tensor_1.reshape(-1, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [21]:
tensor_1 = tensor_1.reshape(1, 3, 3)
tensor_1

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [22]:
tensor_1[0][1]

tensor([4., 5., 6.])